
- name: Generate cluster dns installation yaml file
  template:
    src: "{{ role_path }}/templates/coredns.yaml.j2" 
    dest: "{{ config_dir }}/coredns.yaml"

- name: Apply cluser dns service 
  command: kubectl apply -f {{ config_dir }}/coredns.yaml 
