apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linus-cluster-pod-watcher
  namespace: walnuts
subjects:
- kind: User
  name: linus
  apiGroup: rbac.authorization.k8s.io
roleRef:
 kind: Role
 name: cluster-pod-watcher
 apiGroup: rbac.authorization.k8s.io
