apiVersion: v1
kind: Namespace
metadata:
    name: dev
---
apiVersion: v1
kind: Namespace
metadata:
    name: test
---
apiVersion: v1
kind: Namespace
metadata:
    name: prod
---
apiVersion: v1
kind: Pod
metadata:
  name: cherry
  namespace: dev
spec:
  containers:
    - name: pomegranate-seed
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: mango
  namespace: prod
spec:
  containers:
    - name: pina-colada
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: apricot
  namespace: test
spec:
  containers:
    - name: banana-boat
      image: nginx
