apiVersion: batch/v1
kind: Job 
metadata:
  name: echocompleteneverends
spec: 
  template:
    metadata:
      name: echocompleteneverends
    spec:
      containers:
      - name: echo
        image: alpine:3.2
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10; done"]
      restartPolicy: Never
