apiVersion: v1
data:
  nineteen-eighty-four: |
    It was a bright cold day in April, and the clocks were striking thirteen.
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-22T22:42:01Z"
  name: nineteen-eighty-four
  namespace: default
  resourceVersion: "26739"
  selfLink: /api/v1/namespaces/default/configmaps/nineteen-eighty-four
  uid: 8354a11a-33db-4c6a-aba6-57aba62be264
