apiVersion: v1
kind: Pod
metadata:
  name: michael
  labels:
    band: monkees
    role: guitar 
spec:
  containers:
  - name: band
    image: nginx
  tolerations:
  - key: band
    operator: Equal
    value: monkees
    effect: NoSchedule
